### ISSUE TITLE
sitemap权重和时间错误

### ISSUE THREAD

**Issue by xus66666** [halo-dev/plugin-sitemap#10]
sitemap的权重和时间错误,时间应该是文章发布时间,现在全部都是打开sitemap的时间
<img width="972" alt="image" src="https://github.com/halo-sigs/plugin-sitemap/assets/68573596/b3a066ce-6bda-4b01-8e4d-10a61c59d9a1">
<img width="919" alt="image" src="https://github.com/halo-sigs/plugin-sitemap/assets/68573596/3e3c64c0-64ca-4be7-875b-002082f28e94">

**Comment by carolcoral** [comment]
源码中权重是固定值，时间也是取的服务器时间，这个要改，看后面我有时间可以去试试改。

**Comment by guqing** [comment]
为什么说权重错误，那权重应该是多少呢

**Comment by carolcoral** [comment]
> 为什么说权重错误，那权重应该是多少呢

ta应该是期望可以对每个地址的权重进行区分，而不是统一的权重导致文章和tag等无法进行排序。
在我提交的PR中对该问题进行了修改，支持自定义权重设置(仅对文章生效)，为了保持基准线一致，同时修改默认全局权重为`1.0`作为基础值
