### ISSUE TITLE
插件生成site.xml内的域名后面带数字

### ISSUE THREAD

**Issue by ghfkui** [halo-dev/plugin-sitemap#11]
插件version：1.02
`<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
  <url>
    <loc>http://xxx.com:57555/article/2315515151</loc>
    <lastmod>2023-08-08T18:18:16+08:00</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>http://xxx.com:57555/article/1686221599417</loc>
    <lastmod>2023-08-08T18:18:16+08:00</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
  </url>
</urlset>`
域名后面会跟一串数字，看着像端口号。这是什么原因？过一段时间重新打开数字会有变化

**Comment by carolcoral** [comment]
端口应该不是随机端口，是你原始站点的端口，可以用我的升级版去自定义：https://github.com/carolcoral/plugin-sitemap/releases/tag/v1.0.3

**Comment by ruibaby** [comment]
修改 halo.external-url 即可。

/close
