### ISSUE TITLE
支持robots.txt

### ISSUE THREAD

**Issue by AirboZH** [halo-dev/plugin-sitemap#18]
设置效果如图
![image](https://github.com/halo-sigs/plugin-sitemap/assets/50261327/970e78ac-7cf1-48b5-b329-a27b42da6388)

### 有几个问题：
1. 规则设置使用`select`选择还是text全部由用户手写
下拉方便一些，但是手写扩展写和自定义程度高一些，或者直接textarea全部交给用户处理
如果下拉菜单的话还有一些非扩展标准协议是否支持，如：
> Crawl-delay指令
几大抓取工具支持Crawl-delay参数，设置为多少秒，以等待同服务器之间连续请求：[4][5]
User-agent: *
Crawl-delay: 10

2. sitemap是默认就在robots.txt最后加上`Sitemap: <http://www.example.com/sitemap.xml>`，还是留一个输入框让用户输入

主要是如何平衡高自定义和便捷性

还有其他需求建议么🫡

**Comment by ruibaby** [comment]
我觉得直接一个 Textarea 就行了，默认设置为：

```
User-agent: *
Disallow: 
Disallow: /console
Sitemap: sitemap.xml
```

**Comment by AirboZH** [comment]
> 我觉得直接一个 Textarea 就行了，默认设置为：
> 
> ```
> User-agent: *
> Disallow: 
> Disallow: /console
> Sitemap: sitemap.xml
> ```

那就这么做吧
