### ISSUE TITLE
外部访问地址不支持反向代理吗

### ISSUE THREAD

**Issue by XJY00** [halo-dev/plugin-sitemap#32]
在提交谷歌网站地图时发现sitemap地址，全部都是halo外部访问地址的 localhost:端口，
可是我不怎么会修改反代，能给一个自定义访问地址的选项吗？

**Comment by guqing** [comment]
参考文档 [运行参数详解](https://docs.halo.run/getting-started/install/docker-compose#:~:text=%E5%A4%96%E9%83%A8%E8%AE%BF%E9%97%AE%E9%93%BE%E6%8E%A5%EF%BC%8C%E5%A6%82%E6%9E%9C%E9%9C%80%E8%A6%81%E5%9C%A8%E5%85%AC%E7%BD%91%E8%AE%BF%E9%97%AE%EF%BC%8C%E9%9C%80%E8%A6%81%E9%85%8D%E7%BD%AE%E4%B8%BA%E5%AE%9E%E9%99%85%E8%AE%BF%E9%97%AE%E5%9C%B0%E5%9D%80) 修改你的外部访问地址为域名，这与反向代理没有关系

/kind support

**Comment by XJY00** [comment]
谢谢你，我改好了。
